Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,10 +30,13 @@ jobs:
           cache: 'npm'
       
       - name: Install dependencies
-        run: npm ci --legacy-peer-deps
+        run: npm install --legacy-peer-deps
       
       - name: Build
-        run: npm run build
+        run: |
+          npm run build
+          ls -la
+          ls -la out || echo "out directory not found"
       
       - name: Setup Pages
         uses: actions/configure-pages@v4
